export const DDL_TEMPLATE = [
  "-- ╔══════════════════════════════════════════════════╗",
  "-- ║         PLANTILLA DDL — Nueva Tabla             ║",
  "-- ╚══════════════════════════════════════════════════╝",
  "",
  "-- Ajusta el nombre, columnas y restricciones según tu esquema.",
  "",
  "CREATE TABLE IF NOT EXISTS mi_tabla (",
  "    id          BIGSERIAL      PRIMARY KEY,",
  "    nombre      VARCHAR(255)   NOT NULL,",
  "    descripcion TEXT,",
  "    activo      BOOLEAN        NOT NULL DEFAULT TRUE,",
  "    creado_en   TIMESTAMPTZ    NOT NULL DEFAULT NOW(),",
  "    actualizado TIMESTAMPTZ    NOT NULL DEFAULT NOW()",
  ");",
  "",
  "-- Índice en columnas de búsqueda frecuente",
  "CREATE INDEX IF NOT EXISTS idx_mi_tabla_nombre",
  "    ON mi_tabla (nombre);",
  "",
  "-- Trigger para actualizar 'actualizado' automáticamente",
  "-- (requiere función update_timestamp() en tu schema)",
  "-- CREATE TRIGGER trg_mi_tabla_updated",
  "--     BEFORE UPDATE ON mi_tabla",
  "--     FOR EACH ROW EXECUTE FUNCTION update_timestamp();",
].join("\n");
